INSERT INTO CLIENTES (ID_CLIENTE,DNI,APELLIDO_CLIENTE,NOMBRE_CLIENTE) VALUES (1,'45492374','FLORES QUISPE','CHRISTIAN GUILLERMO');
INSERT INTO CLIENTES (ID_CLIENTE,DNI,APELLIDO_CLIENTE,NOMBRE_CLIENTE) VALUES (2,'42020456','RONDON LIZARRE','RAMIRO REMEN');
INSERT INTO CLIENTES (ID_CLIENTE,DNI,APELLIDO_CLIENTE,NOMBRE_CLIENTE) VALUES (3,'09684547','RAMIREZ RUESTA','RENZO RODOLFO');

INSERT INTO TIPOS_TARJETA (ID_TIPO_TARJETA,NOMBRE_TIPO_TARJETA) VALUES (1,'CLASICA');
INSERT INTO TIPOS_TARJETA (ID_TIPO_TARJETA,NOMBRE_TIPO_TARJETA) VALUES (2,'ORO');
INSERT INTO TIPOS_TARJETA (ID_TIPO_TARJETA,NOMBRE_TIPO_TARJETA) VALUES (3,'BLACK');
